language: node_js
node_js:
- '6'
- '6.1'
- '5'
- '5.11'
env:
  secure: GBiBnI9fDdvtVnAfeovoQa4WwXgnMsmIEFA7zrqFP35KWlBxY5vT7Bxpr5/KuieSarY49B5enbvRafPwdkjkylvsHcV6CHz7k8iM/VmwR5c8zib619tWakV7qft/hS2hzHMiXvDUU13xwcosecv237VWO/S02oDDbK8iUkIz9BMhoyL7bCCFE2fyUYsMYi09xT4FykVVUCAVwt++i5XF4rB+EV2XwATP1F99L+WBLZt1DSIOpGGf4/23u5N8PWXRV0M+rNsfWejILxpP0ArahQA0wND15VNolBbkXj3nMwbzvEXaHXYH2BHIhXM7nozxWLjKOVVzYewYZJ+xk0AgZPwZCtENakZbUUu/3g3v8E6GESUvSex57H5xTWQpxlM6i3/qen7CKlJit5bApID5GH8EOKtAt+uSC2sXLI7pKTF2WlbKep3qyPF3uvSHM1eTwPJ9xklkYybXRHB+R3LGTs1FQmzln4DK92psRHuaJ+H/Ai7yIbBAWt5PTFPFZpo9M9LlzF6TZrpQ3R25c/PLLsd5jsuoWpoB9crqND8UpQygNzEhOZAZIbEuKJs0a66bQyO398+dZ5lqmUZDwHtS9wJ4pi7v6aAfNrDmTv89J+0a7P9aZXCgnZqjbXUd9jY+feFEocJBQpguQNLvCHGOzy+6pmGq6ZmbYukLUaSsPnw=
